dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

addons:
      - chrome:stable

cache:
  directories:
    - ./node_modules
before_install: cd DemoOne

install:
  - npm install

script:
  - xvfb ng test 
