matrix:
  include:
    - language: python
      python:
        - "3.7.3"
      cache: pip
      install:
        - pip install -r requirements.txt
      script:
        - python3 encUnitTests.py
        -python3 faceUnitTests.py